export enum notification {
    GET_FAIL = 'Lấy danh sách thất bại!',
    CREATE_SUCCESS = 'Tạo mới thành công!',
    CREATE_FAIL = 'Tạo mới thất bại!',
    UPDATE_SUCCESS = 'Cập nhật thành công!',
    UPDATE_FAIL = 'Cập nhật thất bại!',
    UPDATE_PASS_SUCCESS = 'Đặt lại mật khẩu thành công!',
    UPDATE_PASS_FAIL = 'Đặt lại mật khẩu thất bại!',
    DELETE_SUCCESS = 'Xóa thành công!',
    DELETE_FAIL = 'Xóa thất bại!',
    RESEND_SUCCESS = 'Gửi lại thành công!',
    RESEND_FAIL = 'Gửi lại thất bại!',
    SUCCESS = 'Thành công!',
    FAIL = 'Thất bại!',
    MESSAGE_ERROR = 'Có lỗi xảy ra!',
    MESSAGE_ERROR_SEARCH = 'Không tìm thấy tài liệu!',
    MESSAGE_ERROR_LOAD = 'Có lỗi xảy ra, bạn cần tải lại trang web!',
    MESSAGE_VALIDATE = 'Kiểm tra lại dữ liệu nhập!',
    SEND_EMAIL_SUCCESS = 'Gửi email thành công!',
    SEND_EMAIL_FAIL = 'Gửi email thất bại!',
    CHECK_SUCCESS = 'Kiểm tra thành công!',
    CHECK_FAIL = 'Kiểm tra thất bại!',
    NOTIFY_READ = "Đọc thông báo!",
    NOTIFY_DELETE = "Gỡ thông báo!",
    FILE_DOES_NOT_EXIST = "File không tồn tại!",
    FILE_UPLOAD_SUCCESS = "Tải lên file thành công!",
    CTS_NOT_FOUND = "Không tìm thấy chứng thư số!"
}
